name: wikimedia/extensions
on:  
  push:    
    branches:      
        - master 
    
jobs:  
  publish-gpr:    
    runs-on: ubuntu-latest    
  steps:      
    - uses: actions/checkout@v2      
    - uses: actions/setup-node@v2        
      with:          
        node-version: 14          
        registry-url: https://npm.pkg.github.com/      
    - run: npm install      
    - run: npm test      
    - run: npm publish        
  env:NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}